# Use root/example as user/password credentials
version: '4.1'

services:
  db:
    image: mysql
    restart: always
    ports:
      - 5544:3306
    environment:
      MYSQL_DATABASE: USERSDB
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
